name: CD
on:
  push:
    branches: [main]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: repo
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "repo"

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
          cache-dependency-path: repo/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: build carbotracker app
        run: npm run build -- --baseHref="/carbotracker/" --outputPath ../../app

      - name: revert changes and checkout app-carbotracker branch
        run: |
          git stash -a
          git checkout -f app-carbotracker
        working-directory: repo

      - name: copy app files
        run: cp $GITHUB_WORKSPACE/../app/. $GITHUB_WORKSPACE/repo -a
        working-directory: /
        
      - name: add and commit
        uses: EndBug/add-and-commit@v9
        with:
          cwd: './repo'
          default_author: github_actions
          message: 'Release new app version'
          new_branch: app-carbotracker
